# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe9a049dcb26070c6fba9965df7fcf2ee6c7c82f174663080c9ebbf1744cebba844c97a595165bb7af1ed7ae446aa46816227a017658c56973eb4936d759dcc5

test:
  secret_key_base: 94e5b47d62dafa630c0745740e0075cf9f6ff319228d0526070b35ffacf6c8fca3ced4e2433db0101fd8fc077aadd9291a6778005d559bc672781322309c71d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
